import React, { useState } from 'react';
import { View, Text, StyleSheet, ScrollView, TouchableOpacity, Image, Dimensions, Share, ActivityIndicator, Alert } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { LinearGradient } from 'expo-linear-gradient';
import { StatusBar } from 'expo-status-bar';
import PalmScanner from '@/components/PalmScanner';
import { Ionicons, MaterialCommunityIcons } from '@expo/vector-icons';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import Animated, { FadeInDown, FadeInUp, Layout } from 'react-native-reanimated';
import { useTheme } from '@/hooks/use-theme';
import { Branding, Colors } from '@/constants/theme';
import { authApi, palmApi } from '@/services/api';

const { width, height } = Dimensions.get('window');

export default function MarriagePalmScreen() {
    const insets = useSafeAreaInsets();
    const [result, setResult] = useState<any>(null);
    const [printing, setPrinting] = useState(false);
    const [userGender, setUserGender] = useState<'male' | 'female' | null>(null);

    React.useEffect(() => {
        const fetchUser = async () => {
            try {
                const me = await authApi.getMe();
                if (me && me.gender) {
                    setUserGender(me.gender.toLowerCase() as any);
                }
            } catch (e) {
                console.log('Error fetching user for palm scan', e);
            }
        };
        fetchUser();
    }, []);

    const exportPDF = async () => {
        try {
            setPrinting(true);
            const html = `
                <html>
                <body style="font-family: sans-serif; padding: 40px; background: #000000; color: #FFFFFF;">
                    <h1 style="color: ${Branding.gold}; text-align: center;">Palmistry Analysis Report</h1>
                    <hr style="border-color: rgba(212, 175, 55, 0.3);" />
                    <div style="margin-top: 30px;">
                        <h2 style="color: ${Branding.gold};">Life Line / வாழ்க்கை ரேகை</h2>
                        <p>${result.analysis.life_line}</p>
                    </div>
                    <div style="margin-top: 20px;">
                        <h2 style="color: ${Branding.gold};">Heart Line / இதய ரேகை</h2>
                        <p>${result.analysis.heart_line}</p>
                    </div>
                    <div style="margin-top: 20px;">
                        <h2 style="color: ${Branding.gold};">Marriage / திருமணம்</h2>
                        <p>${result.analysis.marriage}</p>
                    </div>
                    <div style="margin-top: 30px; padding: 20px; background: rgba(212,175,55,0.1); border-radius: 10px;">
                        <h2 style="color: ${Branding.gold}; margin-top: 0;">Summary</h2>
                        <p>${result.analysis.summary}</p>
                    </div>
                    <footer style="margin-top: 50px; text-align: center; font-size: 12px; color: #888;">
                        Generated by Austro - Astrology & Palmistry App
                    </footer>
                </body>
                </html>
            `;
            const { uri } = await Print.printToFileAsync({ html });
            await Sharing.shareAsync(uri, { UTI: '.pdf', mimeType: 'application/pdf' });
        } catch (error) {
            Alert.alert('Export Failed', 'Unable to create PDF');
        } finally {
            setPrinting(false);
        }
    };

    const [loading, setLoading] = useState(false);

    const handlePalmResult = async (scanRes: any) => {
        try {
            setLoading(true);
            const me = await authApi.getMe();
            
            // 1. Integrated Python AI Processor
            const analysis = await palmApi.analyze({
                capturedImage: scanRes.capturedImage,
                user_id: me?.id
            });

            if (analysis.success) {
                setResult({
                    confidence: 0.98,
                    capturedImage: analysis.processed_image.split('base64,')[1],
                    tamil_results: {
                        summary: analysis.insight || "உங்களது கரத்தின் ரேகைகள் திருமண வாழ்க்கையில் மிகுந்த மகிழ்ச்சியை முன்னறிவிக்கின்றன.",
                        lifeLine: `ஆரோக்கியமான ஆயுள் ரேகை (ஸ்கோர்: ${analysis.lines_count}).`,
                        heartLine: "அன்பு மற்றும் பாசம் நிறைந்த இதய ரேகை காணப்படுகிறது.",
                        marriageLine: "உன்னதமான வரன் மற்றும் மகிழ்ச்சியான இல்லறம் அமையும்."
                    }
                });
            } else {
                throw new Error(analysis.error || "Vision Clouded");
            }

        } catch (error: any) {
            console.error('Marriage Analysis Error:', error);
            Alert.alert('Analysis Failed', 'Unable to reach the Divine Processor. Verify your connection.');
        } finally {
            setLoading(false);
        }
    };

    if (loading) {
        return (
            <View style={{ flex: 1, backgroundColor: Branding.black, justifyContent: 'center', alignItems: 'center' }}>
                <ActivityIndicator size="large" color={Branding.gold} />
                <Text style={{ color: Branding.gold, marginTop: 20, fontSize: 16, fontWeight: 'bold' }}>ANALYZING DESTINY...</Text>
            </View>
        );
    }

    if (!result) {
        return (
            <View style={{ flex: 1, backgroundColor: Branding.black }}>
                <PalmScanner
                    title="Scan Groom's Palm"
                    onResult={handlePalmResult}
                />
            </View>
        );
    }

    return (
        <View style={{ flex: 1, backgroundColor: Branding.black }}>

            <ScrollView 
                style={{ flex: 1 }}
                contentContainerStyle={[styles.scrollContent, { paddingBottom: insets.bottom + 100 }]} 
                showsVerticalScrollIndicator={false}
            >
                {/* Hero Section */}
                <View style={styles.imageHeader}>
                    <Image
                        source={{ uri: `data:image/png;base64,${result.capturedImage}` }}
                        style={styles.backgroundImage}
                        resizeMode="cover"
                    />
                    <LinearGradient
                        colors={['transparent', 'rgba(0,0,0,0.4)', Branding.black]}
                        style={styles.imageOverlay}
                    />

                    <View style={[styles.headerContentFixed, { top: 20 }]}>
                        <TouchableOpacity style={styles.iconBtnHeader} onPress={() => setResult(null)}>
                            <Ionicons name="arrow-back" size={24} color="#FFF" />
                        </TouchableOpacity>
                        <View style={styles.headerTitleContainer}>
                            <Text style={[styles.headerTitle, { color: '#FFF' }]}>Destiny Scan</Text>
                            <Text style={styles.headerSubtitle}>Marriage Alignment</Text>
                        </View>
                        <TouchableOpacity style={styles.iconBtnHeader} onPress={exportPDF}>
                            <Ionicons name="share-outline" size={24} color="#FFF" />
                        </TouchableOpacity>
                    </View>

                    <Animated.View entering={FadeInUp.delay(200)} style={styles.scoreBadge}>
                        <Text style={styles.scoreLabel}>MATCH SCORE</Text>
                        <Text style={styles.scoreValue}>{Math.round((result.confidence || 0.88) * 100)}%</Text>
                    </Animated.View>
                </View>

                <View style={styles.content}>
                    {/* Summary Card */}
                    <Animated.View entering={FadeInDown.delay(300)} style={styles.summaryCard}>
                        <LinearGradient 
                            colors={['rgba(212,175,55,0.15)', 'transparent']} 
                            style={styles.summaryGradient} 
                        />
                        <View style={styles.summaryHeader}>
                            <MaterialCommunityIcons name="crystal-ball" size={24} color={Branding.gold} />
                            <Text style={[styles.boxTitle, { color: Branding.gold, fontSize: 16 }]}>Palm Summary • சுருக்கம்</Text>
                        </View>
                        <Text style={styles.boxText}>{result.tamil_results ? result.tamil_results.summary : result.analysis.summary}</Text>
                    </Animated.View>

                    <Text style={[styles.sectionTitle, { color: '#FFF' }]}>Line Analysis • ரேகை ஆய்வுகள்</Text>
                    
                    <View style={styles.resultGrid}>
                        <Animated.View entering={FadeInDown.delay(400)} style={styles.glowBox}>
                            <View style={styles.boxHeader}>
                                <View style={styles.miniIconCircle}>
                                    <Ionicons name="heart" size={16} color={Branding.gold} />
                                </View>
                                <Text style={[styles.boxTitle, { color: Branding.gold }]}>Heart Line</Text>
                            </View>
                            <Text style={styles.boxText}>{result.tamil_results ? result.tamil_results.heartLine : result.analysis.heart_line}</Text>
                        </Animated.View>

                        <Animated.View entering={FadeInDown.delay(500)} style={styles.glowBox}>
                            <View style={styles.boxHeader}>
                                <View style={styles.miniIconCircle}>
                                    <Ionicons name="flash" size={16} color={Branding.gold} />
                                </View>
                                <Text style={[styles.boxTitle, { color: Branding.gold }]}>Life Line</Text>
                            </View>
                            <Text style={styles.boxText}>{result.tamil_results ? result.tamil_results.lifeLine : result.analysis.life_line}</Text>
                        </Animated.View>

                        <Animated.View entering={FadeInDown.delay(600)} style={styles.glowBoxFull}>
                            <View style={styles.boxHeader}>
                                <View style={styles.miniIconCircle}>
                                    <Ionicons name="ribbon" size={16} color={Branding.gold} />
                                </View>
                                <Text style={[styles.boxTitle, { color: Branding.gold }]}>Marriage Prediction</Text>
                            </View>
                            <Text style={styles.boxText}>{result.tamil_results ? result.tamil_results.marriageLine : result.analysis.marriage}</Text>
                        </Animated.View>
                    </View>

                    <Animated.View entering={FadeInDown.delay(700)} style={styles.actionRow}>
                        <TouchableOpacity style={[styles.exportBtn, { backgroundColor: Branding.gold }]} onPress={exportPDF} disabled={printing}>
                            {printing ? (
                                <ActivityIndicator color={Branding.black} size="small" />
                            ) : (
                                <>
                                    <Ionicons name="download-outline" size={20} color={Branding.black} />
                                    <Text style={[styles.exportText, { color: Branding.black }]}>Save Report</Text>
                                </>
                            )}
                        </TouchableOpacity>

                        <TouchableOpacity style={styles.shareBtn} onPress={() => setResult(null)}>
                            <Ionicons name="refresh" size={20} color={Branding.gold} />
                            <Text style={[styles.shareText, { color: Branding.gold }]}>New Scan</Text>
                        </TouchableOpacity>
                    </Animated.View>
                </View>
            </ScrollView>
        </View>
    );
}

const styles = StyleSheet.create({
    scrollContent: { flexGrow: 1 },
    imageHeader: { height: height * 0.45, width: '100%', position: 'relative' },
    backgroundImage: { width: '100%', height: '100%', opacity: 0.7 },
    imageOverlay: { ...StyleSheet.absoluteFillObject },
    headerContentFixed: { 
        position: 'absolute', 
        left: 0, 
        right: 0, 
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 20,
        zIndex: 10
    },
    iconBtnHeader: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: 'rgba(255, 255, 255, 0.1)',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.1)'
    },
    headerTitleContainer: { alignItems: 'center' },
    headerTitle: { fontSize: 20, fontWeight: 'bold' },
    headerSubtitle: { color: Branding.gold, fontSize: 10, marginTop: 4, letterSpacing: 1, textTransform: 'uppercase' },
    scoreBadge: { 
        position: 'absolute', 
        bottom: 30, 
        left: 20, 
        backgroundColor: 'rgba(212,175,55,0.1)', 
        paddingHorizontal: 15, 
        paddingVertical: 8, 
        borderRadius: 12,
        borderLeftWidth: 3,
        borderLeftColor: Branding.gold
    },
    scoreLabel: { color: Branding.gold, fontSize: 9, fontWeight: 'bold', letterSpacing: 1 },
    scoreValue: { color: '#FFF', fontSize: 20, fontWeight: '800' },
    content: { padding: 20, marginTop: -20 },
    summaryCard: { 
        backgroundColor: 'rgba(25,25,25,1)', 
        borderRadius: 25, 
        padding: 25, 
        borderWidth: 1, 
        borderColor: 'rgba(212,175,55,0.2)',
        overflow: 'hidden',
        marginBottom: 30
    },
    summaryGradient: { position: 'absolute', top: 0, left: 0, right: 0, height: 80 },
    summaryHeader: { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 15 },
    sectionTitle: { fontSize: 18, fontWeight: 'bold', marginBottom: 20 },
    resultGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between' },
    glowBox: { 
        width: '48%', 
        backgroundColor: 'rgba(255,255,255,0.03)', 
        padding: 18, 
        borderRadius: 22, 
        marginBottom: 15, 
        borderWidth: 1, 
        borderColor: 'rgba(255,255,255,0.05)',
    },
    glowBoxFull: { 
        width: '100%', 
        backgroundColor: 'rgba(255,255,255,0.03)', 
        padding: 18, 
        borderRadius: 22, 
        marginBottom: 15, 
        borderWidth: 1, 
        borderColor: 'rgba(255,255,255,0.05)',
    },
    boxHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 10, gap: 10 },
    miniIconCircle: { width: 30, height: 30, borderRadius: 15, backgroundColor: 'rgba(212,175,55,0.1)', justifyContent: 'center', alignItems: 'center' },
    boxTitle: { fontWeight: 'bold', textTransform: 'uppercase', letterSpacing: 0.5 },
    boxText: { color: 'rgba(255,255,255,0.7)', fontSize: 13, lineHeight: 22 },
    actionRow: { marginTop: 20, flexDirection: 'row', gap: 12 },
    exportBtn: { flex: 1.5, height: 55, borderRadius: 28, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 10 },
    exportText: { fontWeight: 'bold', fontSize: 14 },
    shareBtn: { flex: 1, height: 55, backgroundColor: 'rgba(212, 175, 55, 0.05)', borderRadius: 28, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 10, borderWidth: 1, borderColor: Branding.gold },
    shareText: { fontWeight: 'bold', fontSize: 14 }
});
